### ISSUE TITLE
Move output folder to target/output ?

### ISSUE THREAD

**Issue by thomaspapiernik** [H-Max/bq2dbt#1]

**Comment by H-Max** [comment]
Can you be more explicit of why we would implement this change ?

Also, we could make the output folder an option in CLI arguments.

**Comment by thomaspapiernik** [comment]
ouput create a new folder who is not in .gitignore file. target should be already in it. An option in cli would be nice :)

**Comment by H-Max** [comment]
I don't undestand, output folder is indeed in gitignore. I guess it depends on where your un the script from (if it's in a dbt project folder, then yes, the output folder is not ignored).

Will add the option to configure output destination

**Comment by H-Max** [comment]
Closed by #2
