### ISSUE TITLE
[Feature request] Allow to pass a dataset / multiples tables

### ISSUE THREAD

**Issue by florian-trehaut** [H-Max/bq2dbt#3]
Thanks for this great repo, I use it nearly every day.

In dbt, it often happen that we want to generate a schema for many tables at the same time. We could do that with a bash script, but it would be better if supported directly by your program. Here's my view of the feature :

* Add a --dataset parameter to only pass project.dataset. By default, the program would get all tables in this dataset and generate a schema.yml
* Add as --filter parameter, so in combinaison with --dataset, we can be more precise of what we want. Because the recommanded naming convention in DBT is well done, it can be very effective.

Here's an example : 
<img width="389" alt="image" src="https://github.com/H-Max/bq2dbt/assets/65036805/9eb2de96-ab43-48ec-a750-31b50d1fd4b5">
Let's say I want to generate all schema for intermediate layer, I would pass only --dataset <project_id>.intermediate
But if I want to generate schema for only contacts in intermediate, I would pass --dataset <project_id>.intermediate --filter int_contacts*. The file name would be int_contacts__models.yaml and would have only int_contacts models

What do you think about that ?

**Comment by H-Max** [comment]
Added in 530d7b696eb35e96101367d9c17444f04d2ca414 !

So it's available since v0.2.5
